### ISSUE TITLE
cpu went to 100% while opening rs files with nightly edition

### ISSUE THREAD

**Issue by halldong** [fannheyward/coc-rust-analyzer#760]
accidentally raise in [wrong place](https://github.com/rust-analyzer/rust-analyzer/issues/9078) before.

```toml:Cargo.toml
cargo-features = ["edition2021"]

[package]
name = "rest_api"
version = "0.1.0"
authors = ["Hall Dong <Hall Dong>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_codegen = "0.4.4"
diesel = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.9.0"
r2d2-diesel = "1.0"
r2d2 = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
custom_derive ="0.1.7"
[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
```

```rust:src/main.rs
fn main() {
    println!("Hello, world!");
}
```
This occurs even `rustup override set nightly` had been executed.

```
user@host ~/l/rest_api (master)# rustup override set nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: override toolchain for '/user/learn/rest_api' set to 'nightly-x86_64-unknown-linux-gnu'
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.54.0-nightly (f58631b45 2021-05-28)

user@host ~/l/rest_api (master)# vim -p src/main.rs Cargo.toml
2 files to edit
```

```
[coc.nvim] rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.
toml file /user/learn/learn6/Cargo.toml, cargo 1.54.0-nightly (e931e4796 2021-05-24): Failed
 to run `cargo metadata --manifest-path /user/learn/learn6/Cargo.toml` in `/user/learn/learn
6`: `cargo metadata` exited with an error: error: failed to parse manifest at `/user/learn/l
earn6/Cargo.toml`
Caused by:
  the cargo feature `edition2021` requires a nightly version of Cargo, but this is the `stab
le` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information abou
t Rust release channels.
  See https://doc.rust-lang.org/cargo/reference/unstable.html#edition-2021 for more informat
ion about using this feature.
Press ENTER or type command to continue
```

```
...
[coc.nvim] rust-analyzer failed to start, run ':CocCommand rust-analyzer.reloadWorkspace' to reload
```
nothing goes better after doing so.

![微信截图_20210531202847](https://user-images.githubusercontent.com/8103074/120193734-563d6080-c24f-11eb-82ae-07f57d89458c.jpg)
![微信截图_20210531203916](https://user-images.githubusercontent.com/8103074/120194605-63a71a80-c250-11eb-8855-021d12a3a9b8.jpg)
